# Generated by Django 5.1.1 on 2024-10-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
