# Generated by Django 4.2 on 2024-11-08 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_clientes_cotizaciones_horario_nomina_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
