# Generated by Django 4.1.2 on 2024-11-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_horario_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='direcccion',
            new_name='calle',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='direccion',
            new_name='calle',
        ),
        migrations.AddField(
            model_name='clientes',
            name='apellido_materno',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='apellido_paterno',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='ciudad',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='codigo_postal',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='numero',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='apellido_materno',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='apellido_paterno',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='codigo_postal',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='numero',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
