# Generated by Django 4.1.2 on 2024-11-15 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_usuarios_calle_remove_usuarios_cod_postal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='empleados',
            name='rfc',
            field=models.CharField(default='', max_length=13, unique=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='empleado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.empleados'),
        ),
    ]
