# Generated by Django 4.1.2 on 2024-11-15 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_horario_usuario_empleados_rfc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='empleado',
        ),
        migrations.AddField(
            model_name='empleados',
            name='horario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.horario'),
        ),
    ]
