# Generated by Django 4.1.2 on 2024-11-16 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_horario_empleado_empleados_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='usuario',
        ),
        migrations.AddField(
            model_name='nomina',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.empleados'),
            preserve_default=False,
        ),
    ]
