# Generated by Django 4.1.2 on 2024-11-16 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_nomina_usuario_nomina_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
