# Generated by Django 4.1.2 on 2024-11-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_nomina_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
