# Generated by Django 5.1.3 on 2024-11-23 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_ventas_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecotizaciones',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='detallecotizaciones',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='devoluciones',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='devoluciones',
            name='venta',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='total_detalle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='correo',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.TextField(max_length=40)),
                ('uv', models.IntegerField()),
                ('pv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cotizacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_u', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_detalle', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Cotizaciones',
        ),
        migrations.DeleteModel(
            name='DetalleCotizaciones',
        ),
        migrations.DeleteModel(
            name='Devoluciones',
        ),
    ]
