# Generated by Django 5.1.3 on 2024-11-23 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_detallecotizaciones_cotizacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='client',
            new_name='cliente',
        ),
    ]
