# Generated by Django 5.1.3 on 2024-11-23 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_client_cotizacion_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Cotizacion',
        ),
        migrations.DeleteModel(
            name='DetalleCotizacion',
        ),
    ]
