# Generated by Django 5.1.3 on 2024-11-23 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_detallecotizacion_cotizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('total_cotizacion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('productos', models.ManyToManyField(related_name='paquetes', to='api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Desglose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_paquete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cotizacion')),
                ('productos', models.ManyToManyField(related_name='desgloses', to='api.producto')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paquete')),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='paquetes',
            field=models.ManyToManyField(related_name='cotizaciones', through='api.Desglose', to='api.paquete'),
        ),
    ]
