# Generated by Django 5.1.3 on 2024-11-23 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_cotizacion_paquete_desglose_cotizacion_paquetes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='paquetes',
        ),
        migrations.RemoveField(
            model_name='desglose',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='productos',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='paquete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.paquete'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desglose',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.producto'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PaqueteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_paquete', to='api.paquete')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
    ]
