# Generated by Django 5.1.3 on 2024-11-23 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_cotizacion_paquetes_remove_desglose_productos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paqueteproducto',
            name='paquete',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='paquete',
        ),
        migrations.RemoveField(
            model_name='paqueteproducto',
            name='producto',
        ),
        migrations.RenameField(
            model_name='cotizacion',
            old_name='referencia',
            new_name='referencia_producto',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.producto'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Desglose',
        ),
        migrations.DeleteModel(
            name='Paquete',
        ),
        migrations.DeleteModel(
            name='PaqueteProducto',
        ),
    ]
